//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F_W2021_991577657
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covid
    {
        public int covidId { get; set; }
        public string iso_code { get; set; }
        public Nullable<int> continentId { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> total_cases { get; set; }
        public Nullable<double> new_cases { get; set; }
        public Nullable<double> new_cases_smoothed { get; set; }
        public string total_deaths { get; set; }
        public string new_deaths { get; set; }
        public Nullable<double> new_deaths_smoothed { get; set; }
        public Nullable<double> total_cases_per_million { get; set; }
        public Nullable<double> new_cases_per_million { get; set; }
        public Nullable<double> new_cases_smoothed_per_million { get; set; }
        public string total_deaths_per_million { get; set; }
        public string new_deaths_per_million { get; set; }
        public Nullable<double> new_deaths_smoothed_per_million { get; set; }
        public string reproduction_rate { get; set; }
        public string icu_patients { get; set; }
        public string icu_patients_per_million { get; set; }
        public string hosp_patients { get; set; }
        public string hosp_patients_per_million { get; set; }
        public string weekly_icu_admissions { get; set; }
        public string weekly_icu_admissions_per_million { get; set; }
        public string weekly_hosp_admissions { get; set; }
        public string weekly_hosp_admissions_per_million { get; set; }
        public string new_tests { get; set; }
        public string total_tests { get; set; }
        public string total_tests_per_thousand { get; set; }
        public string new_tests_per_thousand { get; set; }
        public string new_tests_smoothed { get; set; }
        public string new_tests_smoothed_per_thousand { get; set; }
        public string positive_rate { get; set; }
        public string tests_per_case { get; set; }
        public string tests_units { get; set; }
        public string total_vaccinations { get; set; }
        public string people_vaccinated { get; set; }
        public string people_fully_vaccinated { get; set; }
        public string new_vaccinations { get; set; }
        public string new_vaccinations_smoothed { get; set; }
        public string total_vaccinations_per_hundred { get; set; }
        public string people_vaccinated_per_hundred { get; set; }
        public string people_fully_vaccinated_per_hundred { get; set; }
        public string new_vaccinations_smoothed_per_million { get; set; }
        public Nullable<double> stringency_index { get; set; }
        public Nullable<double> population { get; set; }
        public Nullable<double> population_density { get; set; }
        public Nullable<double> median_age { get; set; }
        public Nullable<double> aged_65_older { get; set; }
        public Nullable<double> aged_70_older { get; set; }
        public Nullable<double> gdp_per_capita { get; set; }
        public string extreme_poverty { get; set; }
        public Nullable<double> cardiovasc_death_rate { get; set; }
        public Nullable<double> diabetes_prevalence { get; set; }
        public string female_smokers { get; set; }
        public string male_smokers { get; set; }
        public Nullable<double> handwashing_facilities { get; set; }
        public Nullable<double> hospital_beds_per_thousand { get; set; }
        public Nullable<double> life_expectancy { get; set; }
        public Nullable<double> human_development_index { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual Location Location { get; set; }
    }
}
